#NAME: Ziying Yu
#EMAIL: annyu@g.ucla.edu
#ID: 105182320

lab1a:lab1a.c
	gcc -g -Wall -Wextra lab1a.c -o lab1a
clean:
	rm -rf lab1a lab1a-105182320.tar.gz
dist:
	tar -czf lab1a-105182320.tar.gz lab1a.c Makefile README
 
	