#Name: Ziying Yu
#Email: annyu@g.ucla.edu
#ID: 105182320

default:
	gcc -o lab4b -g -lm -lmraa -Wall -Wextra lab4b.c	
check:default
	./check.sh
clean:
	rm -f lab4b lab4b-105182320.tar.gz
dist:
	
	tar -czvf lab4b-105182320.tar.gz lab4b.c Makefile README
