#NAME: Ziying Yu, Shuhua Zhan
#EMAIL: annyu@g.ucla.edu, shuhuaucla@gmail.com
#ID:105182320, 705190671

default:
	gcc -o lab3a -g -Wall -Wextra lab3a.c
dist:
	tar -czvf lab3a-105182320.tar.gz lab3a.c README Makefile ext2_fs.h
clean:
	rm -f lab3a lab3a-105182320.tar.gz 